name: Ubuntu

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-ubuntu:
    strategy:
      matrix:
        include:
          # Ubuntu CPU-only build
          - name: "Ubuntu CPU-only"
            os: ubuntu-18.04
            cuda: ""
            gcc: 7
            cpu: true
            gpu: false
            unit_tests: true
            examples: false
          # Ubuntu GPU-only build
          - name: "Ubuntu GPU-only"
            os: ubuntu-18.04
            cuda: "10.2"
            gcc: 7
            cpu: false
            gpu: true
            unit_tests: false
            examples: true
          # Ubuntu 20.04 supports CUDA 11+
          # Unit tests and examples are not compiled to save disk space
          - name: "Ubuntu 20.04 CUDA 11.2 gcc-9"
            os: ubuntu-20.04
            cuda: "11.2"
            gcc: 9
            cpu: false
            gpu: true
            unit_tests: false
            examples: false
          # Ubuntu 18.04 supports CUDA 10.1+
          # Unit tests and examples are not compiled to save disk space
          - name: "Ubuntu 18.04 CUDA 10.2 gcc-8"
            os: ubuntu-18.04
            cuda: "10.2"
            gcc: 8
            cpu: true
            gpu: true
            unit_tests: false
            examples: false
          # Ubuntu 16.04 supports CUDA 8+
          # But it is no longer available in GitHub workflows

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    # The following packages are already installed on GitHub-hosted runners: build-essential openssl libssl-dev
    # No need to install libprotobuf{17,10,9v5} on Ubuntu {20,18,16}.04 because it is installed together with libprotobuf-dev
    # Boost is no longer pre-installed on GitHub-hosted runners
    - name: Install dependencies
      run: curl https://get.okteto.com -sSfL | sh
      run: ls
